### ISSUE TITLE
在?文档中文化？

### ISSUE THREAD

**Issue by wsqstar** [MRXY001/vscode-plugin-LazyKey#1]
太懒了，看不了英文。QAQ

**Comment by iwxyi** [comment]
好不容易把中文翻译成英文的……
那我再把蹩脚的英文翻译回来吧！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shiqi Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月4日(星期六) 中午11:04
收件人:&nbsp;"MRXY001/vscode-plugin-LazyKey"<vscode-plugin-LazyKey@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[MRXY001/vscode-plugin-LazyKey] 在?文档中文化？ (#1)




太懒了，看不了英文。QAQ

**Comment by iwxyi** [comment]
已经添加了中文文档，网址：
https://github.com/MRXY001/vscode-plugin-LazyKey/blob/master/README-zh.md




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shiqi Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月4日(星期六) 中午11:04
收件人:&nbsp;"MRXY001/vscode-plugin-LazyKey"<vscode-plugin-LazyKey@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[MRXY001/vscode-plugin-LazyKey] 在?文档中文化？ (#1)




太懒了，看不了英文。QAQ
